Temporarily disable arm/v5
Failed to compile due to issue linking with libatomic: /usr/bin/ld: /lib/arm-linux-gnueabi/libatomic.so.1: undefined reference to `libat_test_and_set_1_i2'

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113635